const productList = [
  {
    id: 1,
    name: "Penicillin",
    category: "Antibiotic",
    price: 100,
    stock: 173,
    usage: "Treats bacterial infections",
  },
  {
    id: 2,
    name: "Metformin",
    category: "Diabetes Medication",
    price: 50,
    stock: 80,
    usage: "Manages type 2 diabetes",
  },
  {
    id: 3,
    name: "Amoxicillin",
    category: "Antibiotic",
    price: 75,
    stock: 149,
    usage: "Treats bacterial infections",
  },
  {
    id: 4,
    name: "Omeprazole",
    category: "Proton Pump Inhibitor",
    price: 60,
    stock: 164,
    usage: "Reduces stomach acid production",
  },
  {
    id: 5,
    name: "Ciprofloxacin",
    category: "Antibiotic",
    price: 40,
    stock: 115,
    usage: "Treats bacterial infections",
  },
  {
    id: 6,
    name: "Acetaminophen",
    category: "Pain Reliever",
    price: 90,
    stock: 209,
    usage: "Relieves pain and reduces fever",
  },
  {
    id: 7,
    name: "Ibuprofen",
    category: "Nonsteroidal Anti-inflammatory Drug",
    price: 80,
    stock: 180,
    usage: "Relieves pain, inflammation, and fever",
  },
  {
    id: 8,
    name: "Aspirin",
    category: "Nonsteroidal Anti-inflammatory Drug",
    price: 70,
    stock: 135,
    usage: "Relieves pain, inflammation, and fever",
  },
  {
    id: 9,
    name: "Simvastatin",
    category: "Cholesterol Medication",
    price: 55,
    stock: 294,
    usage: "Lowers cholesterol and triglycerides",
  },
  {
    id: 10,
    name: "Levothyroxine",
    category: "Thyroid Medication",
    price: 45,
    stock: 126,
    usage: "Treats hypothyroidism",
  },
  {
    id: 11,
    name: "Lisinopril",
    category: "ACE Inhibitor",
    price: 65,
    stock: 283,
    usage: "Lowers blood pressure",
  },
  {
    id: 12,
    name: "Atorvastatin",
    category: "Cholesterol Medication",
    price: 60,
    stock: 260,
    usage: "Lowers cholesterol and triglycerides",
  },
  {
    id: 13,
    name: "Metoprolol",
    category: "Beta Blocker",
    price: 70,
    stock: 140,
    usage: "Lowers blood pressure and treats angina",
  },
  {
    id: 14,
    name: "Amlodipine",
    category: "Calcium Channel Blocker",
    price: 75,
    stock: 175,
    usage: "Lowers blood pressure and treats angina",
  },
  {
    id: 15,
    name: "Losartan",
    category: "ARB",
    price: 65,
    stock: 120,
    usage: "Lowers blood pressure",
  },
  {
    id: 16,
    name: "Azithromycin",
    category: "Antibiotic",
    price: 50,
    stock: 295,
    usage: "Treats bacterial infections",
  },
  {
    id: 17,
    name: "Gabapentin",
    category: "Anticonvulsant",
    price: 55,
    stock: 205,
    usage: "Treats seizures and nerve pain",
  },
  {
    id: 18,
    name: "Albuterol",
    category: "Bronchodilator",
    price: 70,
    stock: 270,
    usage: "Relieves asthma and COPD symptoms",
  },
  {
    id: 19,
    name: "Prednisone",
    category: "Corticosteroid",
    price: 60,
    stock: 180,
    usage: "Reduces inflammation and suppresses the immune system",
  },
  {
    id: 20,
    name: "Hydrochlorothiazide",
    category: "Diuretic",
    price: 65,
    stock: 195,
    usage: "Treats high blood pressure and edema",
  },
];

export default productList;